global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: gobfd
    static_configs:
      - targets: ["172.25.0.10:9100"]
